orange-plant:
  kite-connect:
    account:
      segment: equity
    api:
      key:
      version: 3
      secret: 
    query-params:
      api-key: api_key
      version: v
    user-id: rb2977
    logging-enabled: true
    login-url: https://kite.trade/connect/login?v={v}&api_key={api_key}
  market:
    eq-exchange: NSE
    fut-opt-exchange: NFO
  trade-preference:
    exchange: NFO
    segments:
      - NSE
      - NFO-FUT
      - NFO-OPT
    instrument: BANKNIFTY
    expiry-start-date: 01-09-20
    expiry-end-date: 27-09-20