orange-plant:
  kite-connect:
    api:
      key:
      version: 3
      secret:
    query-params:
      api-key: api_key
      version: v
    user-id: rb2977
    logging-enabled: true
    login-url: https://kite.trade/connect/login?v={v}&api_key={api_key}
  trade-preference:
    exchange: NFO
    segments:
      - EQ
      - NFO-FUT
      - NFO-OPT
    instrument: BANKNIFTY
    expiry-start-date: 01-08-20
    expiry-end-date: 27-08-20