money-plant:
  market-data:
    ticker-streaming-enabled: true
    ticker-reading-enabled: false
    candle-period: 600
  technical:
    bar-series:
      bar-count: 14
    atr:
      bar-count: 14