money-plant:
  market-data:
    ticker-reading-enabled: false
    ticker-streaming-enabled: true
    ticker-period: 60000
    bar-generation-enabled: true
    candle-period: 300000
  market-simulation:
    is-enabled: true
    simulation-period: 5
    last-traded-price: 25000
    volume-traded: 0
    ltp-start-range: 5
    ltp-end-range: 50
  technical:
    bar-series:
      bar-count: 7
    atr:
      bar-count: 14
    super-trend:
      multiplier: 3