money-plant:
  market-data:
    ticker-streaming-enabled: true
    ticker-reading-enabled: false
    bar-generation-enabled: true
    candle-period: 300000
    ticker-period: 60000
    run-tick-simulator: true
  technical:
    bar-series:
      bar-count: 14
    atr:
      bar-count: 14