money-plant:
  market-data:
    ticker-streaming-enabled: true
    ticker-reading-enabled: true
    bar-generation-enabled: true
    candle-period: 1000
    ticker-period: 10
  technical:
    bar-series:
      bar-count: 14
    atr:
      bar-count: 14